-- Importación de cumpleaños desde la planilla de dotación de agosto de 2026.
-- La comparación por nombre permite volver a ejecutar la carga sin duplicar registros.

create temporary table birthday_import_20260814 (
  name text primary key,
  month smallint not null,
  day smallint not null,
  description text not null
) on commit drop;

insert into birthday_import_20260814 (name, month, day, description)
values
  ('APONTE CONTRERAS PATRICIA MARGARITA', 6, 8, 'Dotación agosto 2026'),
  ('CONSUEGRA PRIETO MARCELA LETICIA', 2, 17, 'Dotación agosto 2026'),
  ('CORTEZ FLORES DAJEETZAY GABRIELLA', 11, 21, 'Dotación agosto 2026'),
  ('GALAZ SAAVEDRA FERNANDO LUIS', 8, 24, 'Dotación agosto 2026'),
  ('GUEVARA CICARDINI FRANCCESCA YOLANDA', 5, 28, 'Dotación agosto 2026'),
  ('JEREZ CUEVAS VALERIA ALEJANDRA', 10, 6, 'Dotación agosto 2026'),
  ('LEIVA FLORES CARLOS IGNACIO', 10, 17, 'Dotación agosto 2026'),
  ('MONARDES GAMBOA FABIOLA ALESSANDRA', 11, 5, 'Dotación agosto 2026'),
  ('SANCHEZ ORELLANA PATRICIA GEMA', 10, 20, 'Dotación agosto 2026'),
  ('CABEZAS DAMIANO PATRICIO ORLANDO', 7, 15, 'Dotación agosto 2026'),
  ('ARAVENA SOTO CARLA ESTEFANY', 10, 22, 'Dotación agosto 2026'),
  ('MORALES ORTEGA SEBASTIAN ARIEL', 11, 25, 'Dotación agosto 2026'),
  ('CARDENAS SILVA HAIDIS', 4, 25, 'Dotación agosto 2026'),
  ('ALVAREZ PAREDES GABRIEL ANGEL', 7, 27, 'Dotación agosto 2026'),
  ('CHACON AGUIRRE LISMARY CAROLINA', 8, 14, 'Dotación agosto 2026'),
  ('CHIRINOS AVILA LIZMARY JOSEFINA', 4, 16, 'Dotación agosto 2026'),
  ('FARRERAS DE FREITES ESTERLIZ CAROLINA', 12, 18, 'Dotación agosto 2026'),
  ('LAZO MINA MARIELA TATIANA', 6, 8, 'Dotación agosto 2026'),
  ('MORALES GUEDEZ MARY HELLEN', 7, 19, 'Dotación agosto 2026'),
  ('PROPHETE . ROLANDO', 10, 1, 'Dotación agosto 2026'),
  ('PUERTA RIVERO STEPHANIE DAIANA', 2, 3, 'Dotación agosto 2026'),
  ('ROJAS GARCIA NAZARETH SINAI', 6, 15, 'Dotación agosto 2026'),
  ('TAPIA BAU YAREK ANDRES', 11, 11, 'Dotación agosto 2026'),
  ('VILLAFAÑA MARTINEZ MARIA SANDRA', 10, 4, 'Dotación agosto 2026'),
  ('CONCHA RIQUELME PAULINA LORETO', 8, 10, 'Dotación agosto 2026'),
  ('ALBARRAN NAVARRO ANDREA DEL CARMEN', 4, 11, 'Dotación agosto 2026'),
  ('FERNANDEZ MEDINA PABLO ESTEBAN', 11, 19, 'Dotación agosto 2026'),
  ('FERNANDEZ VASQUEZ ANGELICA ANDREINA', 12, 7, 'Dotación agosto 2026'),
  ('GUTIERREZ MENA JOCELYN ESTRELLA', 11, 1, 'Dotación agosto 2026'),
  ('MENESES CAYULAO JONATHAN ANDRES', 6, 4, 'Dotación agosto 2026'),
  ('MONTES DE OCA PEGUERO YEIMI MARIA', 1, 1, 'Dotación agosto 2026'),
  ('QUIROZ OVALLE CARLA KAREN', 4, 24, 'Dotación agosto 2026'),
  ('SAEZ GALLARDO PALOMA INTY-MILLARAY', 7, 22, 'Dotación agosto 2026'),
  ('SILVA FIGUEROA NATALY NICOLE ANDREA', 5, 2, 'Dotación agosto 2026'),
  ('TORRES ALBURQUEQUE NATHALY JOCELYN ANTONIA', 10, 19, 'Dotación agosto 2026'),
  ('VARAS LOPEZ ESTRELLA LORENA', 1, 24, 'Dotación agosto 2026'),
  ('ZELADA HUENUL INGRID NATALY', 9, 24, 'Dotación agosto 2026'),
  ('CORDERO GUEDEZ ROSLEIDY ANDREINA', 7, 11, 'Dotación agosto 2026'),
  ('AQUINO FIERRO KARINA PAOLA', 8, 26, 'Dotación agosto 2026'),
  ('GARCIA MENDOZA LOURDES ELENA', 12, 19, 'Dotación agosto 2026'),
  ('GUEDEZ GUEDEZ ROSYELY MARIA', 4, 2, 'Dotación agosto 2026'),
  ('MARTINEZ PEREZ CARLOS ALFREDO', 9, 5, 'Dotación agosto 2026'),
  ('MEDINA DIAZ CESAR YVAN', 3, 6, 'Dotación agosto 2026'),
  ('MEDINA MENDOZA KARINA LISBETH', 12, 12, 'Dotación agosto 2026'),
  ('NAVAS BRICEÑO ANDRES ALBERTO', 4, 13, 'Dotación agosto 2026'),
  ('PABON BOHORQUEZ ANNA PATRICIA', 1, 8, 'Dotación agosto 2026'),
  ('PALNETT PEÑA LISBETH YARIHT', 12, 4, 'Dotación agosto 2026'),
  ('VENTURA RAMIREZ EDUANNYS JULIET', 8, 23, 'Dotación agosto 2026'),
  ('FONTALVO FAIRUZ MARINA', 8, 12, 'Dotación agosto 2026'),
  ('GATICA GONZALEZ VALERIA EUGENIA', 5, 15, 'Dotación agosto 2026'),
  ('AVILA ACOSTA FRAYALI DAYANA', 10, 31, 'Dotación agosto 2026'),
  ('CONTRERAS FLORES CECILIA BEATRIZ', 2, 8, 'Dotación agosto 2026'),
  ('FLORES FLORES RUTH ELIANA', 12, 22, 'Dotación agosto 2026'),
  ('FUENTES MORANTE WILBELYS ELENA', 7, 13, 'Dotación agosto 2026'),
  ('INOSTROZA ALFARO GLADYS ELIANA', 12, 27, 'Dotación agosto 2026'),
  ('INOSTROZA RODRIGUEZ OLGA INES', 8, 17, 'Dotación agosto 2026'),
  ('OGAZ AGUILERA KARINA DEL CARMEN', 6, 18, 'Dotación agosto 2026'),
  ('ORTEGANO BELISARIO BETTY NEIBETH', 2, 28, 'Dotación agosto 2026'),
  ('RETES ARENILLAS ENZO EUGENIO', 11, 8, 'Dotación agosto 2026'),
  ('SALAS ZABALETA MARITZA COROMOTO', 9, 24, 'Dotación agosto 2026'),
  ('HERNANDEZ CARREÑO CRISTIAN EDUARDO', 3, 3, 'Dotación agosto 2026'),
  ('BARRETO NUÑEZ ERIKA CAROLINA', 2, 3, 'Dotación agosto 2026'),
  ('BARRIOS PONCE MELISSA SUE', 4, 13, 'Dotación agosto 2026'),
  ('BRAVO PAEZ DESIREE ANDREINA', 9, 13, 'Dotación agosto 2026'),
  ('CURTI ASENJO MAGDALENA CONSTANZA', 5, 18, 'Dotación agosto 2026'),
  ('FAUNDEZ CONTRERAS PATRICIO ALFREDO', 12, 13, 'Dotación agosto 2026'),
  ('FIGUEROA ALVAREZ SERGIO ALEJANDRO', 5, 23, 'Dotación agosto 2026'),
  ('HERRERA MORALES ALEJANDRA IGNACIA', 1, 28, 'Dotación agosto 2026'),
  ('RETAMAL CONTRERAS LISSET ANDREA', 1, 27, 'Dotación agosto 2026'),
  ('SALAZAR RIVERA IVETTE OMAIRA', 11, 7, 'Dotación agosto 2026'),
  ('SANTELICES SAAVEDRA BARBARA LUISA', 3, 7, 'Dotación agosto 2026'),
  ('SEKI GUILARTE KARI SIONLEE', 6, 15, 'Dotación agosto 2026'),
  ('TORRES BARRAS VANESSA CAROLINA', 1, 11, 'Dotación agosto 2026'),
  ('VERGARA NAVARRO SACHA ANDREA PAOLA PATRICIA', 9, 10, 'Dotación agosto 2026'),
  ('JHONSON NEIRA GUISELA MACARENA', 6, 26, 'Dotación agosto 2026'),
  ('ARANGUIZ POBLETE CAROLINA ANDREA', 3, 21, 'Dotación agosto 2026'),
  ('CAMACHO MOLINA LEILAMAR ELISA', 9, 10, 'Dotación agosto 2026'),
  ('CURIHUINCA NECULPAN CESAR ANTONIO', 10, 30, 'Dotación agosto 2026'),
  ('DAMIANO CORTES JOHANA PATRICIA', 4, 6, 'Dotación agosto 2026'),
  ('GAJARDO MERINO MARTA MARIA', 12, 24, 'Dotación agosto 2026'),
  ('INOSTROZA HERNANDEZ LUIS ALEJANDRO', 11, 7, 'Dotación agosto 2026'),
  ('LINARES DE CARROZ MARINEL CHIQUINQUIRA', 2, 8, 'Dotación agosto 2026'),
  ('MARTINEZ MORAGA BASTIAN EDUARDO', 11, 1, 'Dotación agosto 2026'),
  ('MUÑOZ NOVOA OSCAR ANTONIO', 6, 13, 'Dotación agosto 2026'),
  ('NAVARRO SAN MARTIN FELIPE ORLANDO', 2, 22, 'Dotación agosto 2026'),
  ('PINNA CACERES ESTEBAN ALONSO', 8, 26, 'Dotación agosto 2026'),
  ('REYES GUTIERREZ MARCO EDUARDO', 10, 24, 'Dotación agosto 2026'),
  ('SANDOVAL STURIONE ALEJANDRA JIMENA', 8, 2, 'Dotación agosto 2026'),
  ('MUÑOZ VILLALOBOS CECILIA DEL CARMEN', 9, 6, 'Dotación agosto 2026'),
  ('ALBORNOZ ESVEILE YANIRA PASCALE', 8, 3, 'Dotación agosto 2026'),
  ('ALVAREZ . BRENDA SARAY', 5, 8, 'Dotación agosto 2026'),
  ('CHELO PARDO ESTHEFANIA FRANCISCA', 2, 5, 'Dotación agosto 2026'),
  ('FARIAS CASTILLO JAVIERA ALEXANDRA', 2, 4, 'Dotación agosto 2026'),
  ('MENA BARROS DAVID JESUS', 10, 10, 'Dotación agosto 2026'),
  ('RIQUELME QUIROZ DANIEL CARLOS', 11, 6, 'Dotación agosto 2026'),
  ('ZUÑIGA OLGUIN JOSE PATRICIO', 4, 29, 'Dotación agosto 2026'),
  ('OLAVARRIA BRIONES JESSICA ANDREA', 5, 11, 'Dotación agosto 2026'),
  ('ARIZA RIOS ANDREA ESTEFANI', 1, 23, 'Dotación agosto 2026'),
  ('CACERES TOLEDO HAIDALYA GRACIELA DEL CARMEN', 3, 17, 'Dotación agosto 2026'),
  ('CARDOZO PALOMINO YULIMAR CHIQUINQUIRA', 11, 28, 'Dotación agosto 2026'),
  ('DIAZ RETAMALES BETZABETH GABRIELA', 12, 20, 'Dotación agosto 2026'),
  ('FERNANDEZ GONZALEZ CRISTIAN HECTOR', 7, 20, 'Dotación agosto 2026'),
  ('MARMOL NOVOA LUISANA DEL VALLE', 7, 26, 'Dotación agosto 2026'),
  ('MAYA CAMPOS MARIYAN DEL CARMEN', 4, 13, 'Dotación agosto 2026'),
  ('TUDELA LOPEZ FRANCESCA ALEJANDRA', 6, 24, 'Dotación agosto 2026'),
  ('VARGAS CHIA JOSHUA', 1, 1, 'Dotación agosto 2026'),
  ('ORTEGA . RICARDO JOSE', 4, 27, 'Dotación agosto 2026'),
  ('ALEUANLLI SOTO FRANCISCO IGNACIO', 6, 18, 'Dotación agosto 2026'),
  ('BURBOA HENRIQUEZ MARIA MONICA', 8, 13, 'Dotación agosto 2026'),
  ('CONSUEGRA PARADA SLOBODA DE JESUS', 1, 25, 'Dotación agosto 2026'),
  ('CORTES FERNANDEZ JENNIFFER CECILIA', 7, 6, 'Dotación agosto 2026'),
  ('CORTEZ NAZARENO DAYANA CAMILA', 3, 1, 'Dotación agosto 2026'),
  ('FERNANDEZ AYALA JUANA ROSA', 6, 24, 'Dotación agosto 2026'),
  ('GIL GARCIA CRISTINA MARIA', 7, 21, 'Dotación agosto 2026'),
  ('GONZALEZ ZUÑIGA VICTOR HERNAN', 9, 3, 'Dotación agosto 2026'),
  ('OYARZUN BUSTOS PATRICIA ELIZABETH', 10, 20, 'Dotación agosto 2026'),
  ('SEPULVEDA CALFUQUEO MARIA PIA', 10, 23, 'Dotación agosto 2026'),
  ('AGREDA BORGES NOREANNYS ANTONIETA', 7, 1, 'Dotación agosto 2026'),
  ('BENAVIDES LOBOS JEMIMA ESTER', 9, 3, 'Dotación agosto 2026'),
  ('CALDERON CASTRO ROXANA ANDREA', 7, 24, 'Dotación agosto 2026'),
  ('CORNEJO FLORES CLARA DEL CARMEN', 4, 10, 'Dotación agosto 2026'),
  ('DEL CASTILLO GARCIA MANUEL ANTONIO', 12, 12, 'Dotación agosto 2026'),
  ('GALLEGOS OJEDA LORETO ALEJANDRA', 9, 8, 'Dotación agosto 2026'),
  ('MEDINA LUGO ADELIS RAFAEL', 5, 31, 'Dotación agosto 2026'),
  ('MUÑOZ SANCHEZ MARIA GRACIELA', 12, 18, 'Dotación agosto 2026'),
  ('PRATO DUARTE ERIK ANTONIO', 4, 10, 'Dotación agosto 2026'),
  ('ROBLERO CANTILLANA MANUEL IGNACIO', 1, 11, 'Dotación agosto 2026'),
  ('VASQUEZ SOTO NIEVE ESTER', 1, 10, 'Dotación agosto 2026'),
  ('SOLIS CALABRANO DANIEL ALFREDO', 5, 15, 'Dotación agosto 2026'),
  ('BUSTOS VIVEROS JUAN RICARDO', 4, 30, 'Dotación agosto 2026'),
  ('COTAL RIQUELME DAISY EUGENIA', 7, 2, 'Dotación agosto 2026'),
  ('GONZALEZ GONZALEZ VANESSA DEL CARMEN', 5, 7, 'Dotación agosto 2026'),
  ('GUTIERREZ ORTIZ ADELINA STEPHANIE', 8, 5, 'Dotación agosto 2026'),
  ('HERNANDEZ SANCHEZ MAKARENA NICOLE', 5, 10, 'Dotación agosto 2026'),
  ('LAGOS URZUA PATRICIO ALFREDO', 5, 21, 'Dotación agosto 2026'),
  ('LIRA SILVA GLENDA ALEJANDRA', 6, 23, 'Dotación agosto 2026'),
  ('NAVARRO DIAZ YANNIELLY EDITH', 1, 6, 'Dotación agosto 2026'),
  ('ORELLANA ORELLANA ELIZABETH', 4, 29, 'Dotación agosto 2026'),
  ('ORELLANA ZUÑIGA NICOLAS ANDRES', 2, 24, 'Dotación agosto 2026'),
  ('PERALTA ALDANA DAVINA ANDREA', 1, 13, 'Dotación agosto 2026'),
  ('PROSSER CAMUS MARIA TRINIDAD MARIELA', 4, 10, 'Dotación agosto 2026'),
  ('VEGA SALGADO JULIO ESTEBAN', 1, 9, 'Dotación agosto 2026'),
  ('VARGAS ALVARADO NATALIA ANDREA', 9, 15, 'Dotación agosto 2026'),
  ('AGUIRRE ARRIAGADA JAVIERA FERNANDA', 5, 9, 'Dotación agosto 2026'),
  ('AMPUERO GOMEZ FRANCISCA ANDREA', 10, 16, 'Dotación agosto 2026'),
  ('CABALLERIA CARRASCO AYLINN CONSTANZA', 10, 22, 'Dotación agosto 2026'),
  ('CASTRO RAMIREZ JAVIERA MACARENA', 3, 25, 'Dotación agosto 2026'),
  ('MICHEL ARAVENA CATHERINE JEANNETTE', 11, 18, 'Dotación agosto 2026'),
  ('ROBLES CEA FABIOLA DEL PILAR', 12, 22, 'Dotación agosto 2026'),
  ('SEPULVEDA SANHUEZA GRACIELA SAMADAR', 10, 20, 'Dotación agosto 2026'),
  ('SOTO LEIVA ANA ALEJANDRA', 1, 26, 'Dotación agosto 2026'),
  ('VIVANCO ZUÑIGA CATERINA GRACIELA', 7, 8, 'Dotación agosto 2026'),
  ('ACEVEDO SALCEDO CONSTANZA JAVIERA', 8, 27, 'Dotación agosto 2026'),
  ('AGUILAR NUÑEZ CAMILO ANDRES', 8, 11, 'Dotación agosto 2026'),
  ('BRAVO SANDOVAL CLAUDIA VERONICA', 9, 6, 'Dotación agosto 2026'),
  ('CHIRINOS PIÑA CARMEN ANTONIA', 7, 16, 'Dotación agosto 2026'),
  ('ESPINOZA PALMA NINETTE TAMMY', 2, 10, 'Dotación agosto 2026'),
  ('HIDALGO VASQUEZ SANDRA DEL CARMEN', 6, 23, 'Dotación agosto 2026'),
  ('MOREIRA IGLESIAS SUSAN BEATRIZ', 4, 28, 'Dotación agosto 2026'),
  ('NAVARRETE PARRA EDITH PATRICIA', 5, 4, 'Dotación agosto 2026'),
  ('PEREZ GUERRA LORETO ALEXANDRA', 7, 5, 'Dotación agosto 2026'),
  ('PLATZ AYALA SERGIO HERNAN', 10, 12, 'Dotación agosto 2026'),
  ('SERRANO LEFIMIL MARIA JOSE', 4, 15, 'Dotación agosto 2026'),
  ('VARGAS VARGAS DIEGO MOISES', 10, 18, 'Dotación agosto 2026'),
  ('BRAVO HERNANDEZ RODOLFO ANTONIO', 7, 19, 'Dotación agosto 2026'),
  ('ETCHEVERRY CARDENAS KARIN ANDREA', 1, 13, 'Dotación agosto 2026'),
  ('SEGURA CORDOVA MAURICIO HERNAN', 4, 20, 'Dotación agosto 2026');

update public.birthdays as birthday
set
  month = imported.month,
  day = imported.day,
  description = imported.description,
  active = true
from birthday_import_20260814 as imported
where lower(btrim(birthday.name)) = lower(btrim(imported.name));

insert into public.birthdays (name, month, day, description, active)
select imported.name, imported.month, imported.day, imported.description, true
from birthday_import_20260814 as imported
where not exists (
  select 1
  from public.birthdays as birthday
  where lower(btrim(birthday.name)) = lower(btrim(imported.name))
);
